# config.yaml
opt_params:
  pose_lr: 0.0001
  position_lr_init: 0.000016
  position_lr_final: 0.0000016
  position_lr_max_steps: 2000
  feature_lr: 0.012
  opacity_lr: 0.05
  scaling_lr: 0.002
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densify_grad_threshold: 0.0002
  exposure_lr: 0.01

Training:
  init_itr_num: 3000
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 2.0
  gaussian_reset: 2001
  size_threshold: 20
  window_size: 10
  rgb_boundary_threshold: 0.02
  compensate_exposure: true
  monocular: false
  max_steps: 15000
  rotation_init: True
  lambda_normal: 0.1

Dataset:
  pcd_downsample: 8
  pcd_downsample_init: 4
  point_size: 0.1
  adaptive_pointsize: True
  scale_multiplier: 6.0
  voxel_size_init: 0.03
  voxel_size: 0.05
  max_points_per_voxel: 50
  max_layer: 2